active_artwork_file_path: 'active_artwork.jpg'

kiosk:
  path: 'frame_gray.png'
  inner_width: 1710
  inner_height: 870

pirsensor:
  GPIO_mode: 'BOARD'
  GPIO_sensor: 31
  loop_sleep_sec: 0.1
  screensaver_after_sec: 10

artbutton:
  GPIO_mode: 'BOARD'
  GPIO_button: 15
  image_directory: 'images'
  button_sleep: 1.0

ml_model:
  batch_size: 1
  img_size: 1024
  test_num: 20
  checkpoint_directory: 'ml/checkpoint'
  image_directory: 'images'
  lower_limit_num_images: 200
